### ISSUE TITLE
Chromedriver 2.35 and context errors when switching in and out of iframes

### ISSUE THREAD

**Issue by shermaneric** [blackboard/protractor-sync#59]
Background:
In some of our E2E tests, when upgrading to Chromedriver 2.35, we see erorrs such as this
```
A"code":-32000,"message":"Cannot find context with specified id"}   (Session info: chrome=64.0.3282.140)   (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.4.102-k8s x86_64)


 at WebDriverError (/home/jenkins/workspace/i_feature_chromedriver_2_35-DKH5Z26P7OQLSYGUK4SJHBGK2ZUY2GQOWGKRPWLX7SVDBPT5WQXA/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)

 at Object.checkLegacyResponse (/home/jenkins/workspace/i_feature_chromedriver_2_35-DKH5Z26P7OQLSYGUK4SJHBGK2ZUY2GQOWGKRPWLX7SVDBPT5WQXA/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)


 at parseHttpResponse (/home/jenkins/workspace/i_feature_chromedriver_2_35-DKH5Z26P7OQLSYGUK4SJHBGK2ZUY2GQOWGKRPWLX7SVDBPT5WQXA/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
 at doSend.then.response (/home/jenkins/workspace/i_feature_chromedriver_2_35-DKH5Z ... to equal ''.
```
It appears that this has been logged [in Chromium here](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2198)

Any thoughts, help or workarounds welcome.

I've pushed up some new tests and [upped the Chromedriver version here in this branch as well](https://github.com/blackboard/protractor-sync/tree/feature/2.35_chromedriver)

**Comment by shermaneric** [comment]
ah, resolved with chromedriver 2.36.  sorry.
